In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
df = pd.read_csv("C:/Users/hp/Downloads/smartphone_dataset_1M.csv")
print(df)
df.head()

           brand     model_name       os  price_inr  launch_year  5g_support  \
0         Google    Google_2528  Android      71511         2020           1   
1        Samsung   Samsung_9006  Android      57511         2018           1   
2         Google    Google_2059  Android      76042         2022           0   
3         Realme    Realme_5737  Android      26916         2021           0   
4        OnePlus   OnePlus_5548  Android      31505         2022           1   
...          ...            ...      ...        ...          ...         ...   
999995    Google    Google_9242  Android      58041         2025           1   
999996   OnePlus   OnePlus_7868  Android      44557         2018           1   
999997    Xiaomi    Xiaomi_8446  Android       5000         2021           0   
999998  Motorola  Motorola_5474  Android      16253         2023           0   
999999    Xiaomi    Xiaomi_5680  Android      15041         2023           1   

        dual_sim  expandable_storage  w

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,display_size_inch,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g,thickness_mm
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,...,6.10,AMOLED,120,4657,25,200,16,Wide,175.2,8.29
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,...,5.77,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6,7.41
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,...,6.10,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0,8.89
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,...,6.28,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6,7.67
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,...,6.45,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9,9.41


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 33 columns):
 #   Column                Non-Null Count    Dtype  
---  ------                --------------    -----  
 0   brand                 1000000 non-null  object 
 1   model_name            1000000 non-null  object 
 2   os                    1000000 non-null  object 
 3   price_inr             1000000 non-null  int64  
 4   launch_year           1000000 non-null  int64  
 5   5g_support            1000000 non-null  int64  
 6   dual_sim              1000000 non-null  int64  
 7   expandable_storage    1000000 non-null  int64  
 8   water_resistance      1000000 non-null  int64  
 9   wireless_charging     1000000 non-null  int64  
 10  fingerprint_sensor    1000000 non-null  int64  
 11  face_unlock           1000000 non-null  int64  
 12  gpu_score             1000000 non-null  int64  
 13  cpu_score             1000000 non-null  int64  
 14  screen_to_body_ratio  1000000 non-n

In [7]:
df.size

33000000

In [8]:
df.shape

(1000000, 33)

In [9]:
df.describe

<bound method NDFrame.describe of            brand     model_name       os  price_inr  launch_year  5g_support  \
0         Google    Google_2528  Android      71511         2020           1   
1        Samsung   Samsung_9006  Android      57511         2018           1   
2         Google    Google_2059  Android      76042         2022           0   
3         Realme    Realme_5737  Android      26916         2021           0   
4        OnePlus   OnePlus_5548  Android      31505         2022           1   
...          ...            ...      ...        ...          ...         ...   
999995    Google    Google_9242  Android      58041         2025           1   
999996   OnePlus   OnePlus_7868  Android      44557         2018           1   
999997    Xiaomi    Xiaomi_8446  Android       5000         2021           0   
999998  Motorola  Motorola_5474  Android      16253         2023           0   
999999    Xiaomi    Xiaomi_5680  Android      15041         2023           1   

     

In [10]:
for i in df.columns:
    print(df[i].unique())

['Google' 'Samsung' 'Realme' 'OnePlus' 'Vivo' 'Nothing' 'Apple' 'Oppo'
 'Motorola' 'Xiaomi']
['Google_2528' 'Samsung_9006' 'Google_2059' ... 'Nothing_9484'
 'Nothing_6609' 'Vivo_3480']
['Android' 'iOS']
[ 71511  57511  76042 ... 104062 113988  71971]
[2020 2018 2022 2021 2025 2019 2023 2024]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[1 0]
[ 6850  6100  6862 ... 12588 12675  -726]
[ 8793  7275  9390 ... 15166 -1473 15424]
[88.68 88.02 83.33 ... 91.59 91.92 79.07]
['Metal' 'Glass' 'Plastic']
[5 2 4 6 3 7]
[1 2]
[5.2 5.  5.3 5.1 4.2]
['WiFi 5' 'WiFi 6' 'WiFi 6E']
['Tensor G3' 'A17 Bionic' 'Snapdragon 8 Gen 2' 'Dimensity 900'
 'Exynos 1380' 'Snapdragon 778G' 'Helio G85' 'Snapdragon 680'
 'Dimensity 6020']
[12 16  8  6  4  3]
[128  64 256 512]
[6.1  5.77 6.28 6.45 5.85 6.23 5.95 6.2  6.08 6.49 5.52 6.03 6.37 6.25
 5.67 6.66 6.65 5.97 6.06 6.82 6.24 5.88 5.56 6.89 6.22 6.46 5.53 6.85
 5.6  6.18 6.32 6.74 6.76 6.84 6.47 5.64 6.01 6.67 5.66 6.33 6.51 5.92
 6.87 6.62 5.51 6.55 6.31 6.07 6.5  6.43 5.6

In [11]:
for i in df.columns:
    print(df[i].nunique())

10
89990
2
108967
8
2
2
2
2
2
2
2
14109
17040
2001
3
6
2
5
3
9
6
4
141
3
4
5809
6
6
4
205
1607
251


In [12]:
print("Before duplicates:",df.shape)
df = df.drop_duplicates()
print("After duplicates:",df.shape)

Before duplicates: (1000000, 33)
After duplicates: (1000000, 33)


In [13]:
Q1 = df['price_inr'].quantile(0.25)
Q3 = df['price_inr'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df = df[(df['price_inr'] >= lower) & (df['price_inr'] <= upper)]

print(df.shape)

(969225, 33)


In [14]:
if 'model_name' in df.columns:
    df.drop('model_name', axis=1, inplace=True)

In [15]:
df.head()

,brand,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,fingerprint_sensor,...,display_size_inch,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g,thickness_mm
0,Google,Android,71511,2020,1,1,0,0,1,1,...,6.10,AMOLED,120,4657,25,200,16,Wide,175.2,8.29
1,Samsung,Android,57511,2018,1,0,1,0,0,1,...,5.77,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6,7.41
2,Google,Android,76042,2022,0,1,1,1,0,1,...,6.10,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0,8.89
3,Realme,Android,26916,2021,0,1,0,1,0,1,...,6.28,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6,7.67
4,OnePlus,Android,31505,2022,1,0,0,0,1,1,...,6.45,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9,9.41


In [16]:
X = df.drop('price_inr', axis=1)
y = df['price_inr']

In [17]:
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

print(numeric_features)
print(categorical_features)

Index(['launch_year', '5g_support', 'dual_sim', 'expandable_storage',
       'water_resistance', 'wireless_charging', 'fingerprint_sensor',
       'face_unlock', 'gpu_score', 'cpu_score', 'screen_to_body_ratio',
       'colors_available', 'warranty_years', 'bluetooth_version', 'ram_gb',
       'storage_gb', 'display_size_inch', 'refresh_rate_hz', 'battery_mah',
       'fast_charging_w', 'rear_camera_mp', 'front_camera_mp', 'weight_g',
       'thickness_mm'],
      dtype='object')
Index(['brand', 'os', 'build_material', 'wifi_version', 'chipset',
       'display_type', 'camera_setup'],
      dtype='object')


In [18]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [19]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
from xgboost import XGBRegressor

In [24]:
model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=10,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

In [25]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

In [26]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['launch_year', '5g_support', 'dual_sim', 'expandable_storage',
       'water_resistance', 'wireless_charging', 'fingerprint_sensor',
       'face_unlock', 'gpu_score', 'cpu_score', 'screen_to_body_ratio',
       '...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=10, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [27]:
y_pred = pipeline.predict(X_test)

In [29]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [30]:
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2 Score:", r2)
print("MAE:", mae)
print("RMSE:", rmse)

R2 Score: 0.9852563142776489
MAE: 2117.157470703125
RMSE: 2678.9192783658114


In [31]:
model = pipeline.named_steps['model']

importance = model.feature_importances_

print(importance)

[4.80260642e-05 4.73963701e-05 5.79701555e-05 5.41454792e-05
 5.72310928e-05 6.09308008e-05 7.35863214e-05 6.68111315e-05
 4.87034582e-02 6.64236188e-01 1.13933987e-04 9.52102637e-05
 8.87242641e-05 9.72275739e-05 1.77996848e-02 9.64393912e-05
 1.20890661e-04 1.46435239e-04 1.28221742e-04 1.03479200e-04
 1.17581934e-02 1.01933394e-04 1.28177824e-04 1.29113047e-04
 1.15562089e-01 1.93652026e-02 1.19129440e-03 3.34449625e-03
 4.41575423e-03 8.52944446e-04 1.47306477e-03 1.21357301e-02
 1.08638196e-03 1.07563590e-03 2.07709009e-03 2.44627387e-04
 1.06275009e-04 1.06434709e-04 1.09072018e-04 1.08527267e-04
 1.04709572e-04 1.05208484e-04 7.10997125e-03 7.58322747e-03
 8.14205781e-03 6.90477993e-03 5.61269745e-03 5.45735145e-03
 6.23019645e-03 9.17093735e-03 7.19744293e-03 1.06528183e-04
 2.04591604e-04 1.12704547e-04 1.45449885e-04 1.48720937e-04
 1.35042763e-04 1.43232130e-04 1.22255165e-04 1.45527505e-04
 1.29235865e-04 1.35097158e-04 1.45524755e-04 1.30778571e-04
 1.38401971e-04 1.471786

In [32]:
import pickle

pickle.dump(pipeline, open('smartphone_price_model.pkl', 'wb'))

In [33]:
loaded_model = pickle.load(open('smartphone_price_model.pkl', 'rb'))

In [34]:
import gradio as gr
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import r2_score
from xgboost import XGBRegressor
df = pd.read_csv("C:/Users/hp/Downloads/smartphone_dataset_1M.csv")
df = df.drop_duplicates()
Q1 = df['price_inr'].quantile(0.25)
Q3 = df['price_inr'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[
    (df['price_inr'] >= lower) &
    (df['price_inr'] <= upper)
]
if 'model_name' in df.columns:
    df.drop('model_name', axis=1, inplace=True)
X = df.drop('price_inr', axis=1)
y = df['price_inr']
numeric_features = X.select_dtypes(
    include=['int64', 'float64']
).columns

categorical_features = X.select_dtypes(
    include=['object']
).columns
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=10,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

score = r2_score(y_test, y_pred)

print("R2 Score:", score)

pickle.dump(pipeline, open("smartphone_price_model.pkl", "wb"))


def predict_price(*inputs):

    input_data = pd.DataFrame([inputs], columns=X.columns)

    prediction = pipeline.predict(input_data)[0]

    return f"Predicted Smartphone Price: ₹ {round(prediction, 2)}"


inputs = []

for col in X.columns:

    if col in numeric_features:

        inputs.append(
            gr.Number(label=col)
        )

    else:

        choices = list(df[col].dropna().unique())

        inputs.append(
            gr.Dropdown(
                choices=choices,
                label=col
            )
        )

interface = gr.Interface(
    fn=predict_price,
    inputs=inputs,
    outputs=gr.Textbox(),
    title="Smartphone Price Prediction",
    description="Predict smartphone prices using Machine Learning"
)

interface.launch()

R2 Score: 0.9852563142776489
* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.
